# Generated by Django 5.1.5 on 2025-06-18 17:51

import candidates.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('resume', models.FileField(max_length=500, upload_to=candidates.models.resume_upload_path)),
                ('general_details', models.JSONField(blank=True, null=True)),
                ('feedback_details', models.JSONField(blank=True, null=True)),
                ('scores_lookup', models.JSONField(blank=True, null=True)),
                ('score_details', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('bold_value', models.BooleanField(default=True)),
                ('phase', models.CharField(default='new_applicant', max_length=50)),
                ('comments', models.JSONField(default=candidates.models.default_comments)),
                ('value', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='job.jobopening')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_with', models.JSONField(blank=True, default=list, null=True)),
                ('access_level', models.JSONField(blank=True, default=list, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_access', to='candidates.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeProcessingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='idle', max_length=20)),
                ('n_resumes', models.IntegerField(default=0)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_details_processing_status', to='job.jobopening')),
            ],
        ),
    ]
