# Generated by Django 5.1.5 on 2025-06-18 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_unique_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('role_type', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('level_of_position', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('job_summary', models.TextField(blank=True, null=True)),
                ('key_responsibilities', models.TextField(blank=True, null=True)),
                ('candidate_requirements', models.TextField()),
                ('evaluation_metrics', models.TextField()),
                ('additional_inputs', models.TextField(blank=True, null=True)),
                ('candidates_required', models.IntegerField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('onsite', models.JSONField(blank=True, null=True)),
                ('phase', models.JSONField(default=list)),
                ('salary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.CharField(default='active', max_length=20)),
                ('pointer', models.IntegerField(default=0)),
                ('issues', models.JSONField(blank=True, null=True)),
                ('fixes', models.JSONField(blank=True, null=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserExtendedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_limit', models.IntegerField(default=50)),
                ('no_resumes_left', models.IntegerField(default=50)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_extended_fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
