# Generated by Django 5.1.5 on 2025-06-18 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aspects_all_parameters', models.JSONField(blank=True, default=list, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('overall_score', models.JSONField(blank=True, default=list, null=True)),
                ('group_aspects', models.JSONField(blank=True, null=True)),
                ('group_aspects_name_list', models.JSONField(blank=True, default=list, null=True)),
                ('aspect_pointer', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='job.jobopening')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AspectsProcessingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='processing', max_length=15)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aspects_processing_status', to='job.jobopening')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.TextField()),
                ('evaluation_method', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_parameters', to='job.jobopening')),
            ],
        ),
    ]
